### ISSUE TITLE
Call to undefined function GuzzleHttp\Psr7\try_fopen()

### ISSUE THREAD

**Issue by srakl** [bp-sys/yii2-aws-s3#3]
I'm getting this error 

`Call to undefined function GuzzleHttp\Psr7\try_fopen()`

when i run this code

```
$img  = 'https://blabla.com/imgs/2d1xhg5Vvg2PDSKqq2B6A9EirMk0cmeuc6jZlsg2HXX6VlMB4O77OUdTSxDocmrw1lBpTEWqlk0sEcHDoFrYPXIVEAPPeJirMX6ToMO0CdK84QVCADWcsLdHzpQd';
$result = $s3->commands()->upload('file.jpg', $img)->withAcl('public')->execute();
```

Is this how i copy an image from a url and save it into S3?

**Comment by bpanatta** [comment]
Thanks for pointing up, there was an issue with Guzzle deprecated code.
That is exactly how you should use that.
